apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: infra-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloud-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .R2_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .R2_SECRET_ACCESS_KEY }}
  data:
  - secretKey: R2_ACCESS_KEY_ID
    remoteRef:
      key: R2_ACCESS_KEY_ID
  - secretKey: R2_SECRET_ACCESS_KEY
    remoteRef:
      key: R2_SECRET_ACCESS_KEY
