apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/wekamlesh/k8s-gitops.git'
    targetRevision: HEAD
    path: k8s-manifests
    directory:
      recurse: true
      exclude: 'root-app.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
